# Generated by Django 4.1.7 on 2023-12-11 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_regmodel_addr_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='propic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to='post_images/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('bstatus', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.regmodel')),
            ],
        ),
    ]
