# Generated by Django 4.1.7 on 2023-12-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_regmodel_propic_postmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='category',
            new_name='bcategory',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='content',
            new_name='bcontent',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='image',
            new_name='bimage',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='summary',
            new_name='bsummary',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='title',
            new_name='btitle',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='user',
            new_name='buser',
        ),
    ]
