# Generated by Django 4.1.7 on 2023-12-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_category_postmodel_bcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModel',
            new_name='BlogModel',
        ),
    ]
