# Generated by Django 4.1.7 on 2023-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_postmodel_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='bstatus',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
