# Generated by Django 4.1.7 on 2023-12-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_blogmodel_bstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='bstatus',
            field=models.BooleanField(default=True),
        ),
    ]
